version: "3.8"
services:
  logging:
    build:
      context: .
    volumes:
      - ./:/usr/src/app
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - CHECK_INTERVAL=${CHECK_INTERVAL}
      - CHAT_ID=${CHAT_ID}
      - BOT_TOKEN=${BOT_TOKEN}
